### ISSUE TITLE
arrays transform into objects

### ISSUE THREAD

**Issue by articice** [WebReflection/cloner#1]
Here's a simplified real-life example

```
var deep = require('cloner').deep;

var fare = {
    TotalPrice: "EUR100",
        Directions: [
        [
            {
                from: "IEV",
                to: "BKK"
            },
            {
                from: "IEV",
                to: "BKK"
            }
        ]
    ],

    BookingComponents: [
        {
            TotalPrice: "EUR100"
        }
    ]
};

var fare_copy = deep.copy(fare);

console.log(JSON.stringify(fare_copy));
```

> {"BookingComponents":{"0":{"TotalPrice":"EUR100"}},"Directions":{"0":{"0":{"to":"BKK","from":"IEV"},"1":{"to":"BKK","from":"IEV"}}},"TotalPrice":"EUR100"}

Note how _BookingComponents_ and _Directions_ which were arrays became objects.

**Comment by articice** [comment]
Switched to lodash deepClone, does the job perfectly - order of keys in objects is not mixed, no object to array transformation.

**Comment by WebReflection** [comment]
there's no transformation indeed, it's a JSON/console gotcha, and also `Array.isArray` fails but technically those two are identical:

``` js
Object.getPrototypeOf(fare.Directions) ===
Object.getPrototypeOf(fare_copy.Directions);
```

Unfortunately the `Reflect` utility is not widely available so I'll need to monkey-patch this shenanigan creating a special case for arrays.

Very bad JS behavior, if you ask me. Will fix, thanks.
