### ISSUE TITLE
Some Data Not Merged/Copied, Only Noticed Strings

### ISSUE THREAD

**Issue by jfftck** [WebReflection/cloner#4]
I have a structure like this:

```javascript
{
  items: [
    {
      name: "string",
      details: [{...}],
      Id: "string",
      Id2: "string",
      details2: [{...}],
      words: "",
      text: "string",
      text2: "string"
    }
  ]
}
```

Some of the strings are being excluded in the deep merge, at least the last two strings are skipped. I have rearranged the object of the target and it didn't fix the issue. This is also the same issue for deep copy.

**Comment by WebReflection** [comment]
As you can see from the added test everything is fine.
Look closer, maybe the key order is jut different but the deep copy has same keys and same values.

**Comment by WebReflection** [comment]
please see this PR too:
https://github.com/WebReflection/cloner/pull/2
