### ISSUE TITLE
Date objects being destroyed during merge

### ISSUE THREAD

**Issue by nickyblissAviva** [WebReflection/cloner#6]
Date objects are not being copied correctly when using cloner so they are no longer date objects post merge.

I have found updating the return value for isObject to:
`return value !== null && ( Object.prototype.toString.call( value ) === '[object Object]' || Array.isArray( value ) );`
Seems to fix the issue

**Comment by WebReflection** [comment]
last time I've touched this was 4 years ago, meanwhile `Object.getOwnPropertyDescriptors` (plural) landed, basically removing the need for this module, except for descriptors which value is an object like one.

If you'd like to file a MR for your use cases, I'd be happy to consider it, but as I haven't used myself this module in 4 years, and all modules dependent on this are deprecated or used by nobody, I don't think I'll have any time to deal with this module.

I might, instead, deprecate it right away. Please let me know which option you prefer, thanks.

**Comment by nickyblissAviva** [comment]
@WebReflection How have you go around getOwnPropertyDescriptors only passing references rather than creating copies of the objects and also the lack of support in IE11?

**Comment by WebReflection** [comment]
For IE11 polyfills, the rest is an Object.keys loop away, if the descripror value is type of object, and not null, recursion

**Comment by WebReflection** [comment]
Something like this:

```js
const clone = obj => {
  const descriptors = Object.getOwnPropertyDescriptors(obj);
  Reflect.ownKeys(descriptors).forEach(key => {
    const descriptor = descriptors[key];
    const {value} = descriptor;
    switch (true) {
      case value instanceof Date:
        descriptor.value = new Date(+value);
        break;
      case value instanceof RegExp:
        descriptor.value = new RegExp(value.source, value.flags);
        break;
      case value instanceof Object:
        descriptor.value = clone(value);
        break;
    }
  });
  return Object.create(Object.getPrototypeOf(obj), descriptors);
};
```

**Comment by nickyblissAviva** [comment]
Thank you. Been having issues finding any lightweight/working polyfills for getOwnPropertyDescriptors. The few I have found use Reflect which is also not supported by IE11.

**Comment by WebReflection** [comment]
Ever heard of polyfill.io? It patches IE11 too, with all these things

**Comment by WebReflection** [comment]
btw: https://github.com/ungap/get-own-property-descriptors

**Comment by WebReflection** [comment]
Actually, I've just added [Reflect.ownKeys](https://github.com/ungap/own-keys) polyfill for IE too. Let's simplify the code, assuming you are using a bundler:

```js
import ownKeys from '@ungap/own-keys';
const {create, defineProperty, getOwnPropertyDescriptor, getPrototypeOf} = Object;
const clone = obj => {
  const out = create(getPrototypeOf(obj));
  ownKeys(obj).forEach(key => {
    const descriptor = getOwnPropertyDescriptor(obj, key);
    const {value} = descriptor;
    switch (true) {
      case value instanceof Date:
        descriptor.value = new Date(+value);
        break;
      case value instanceof RegExp:
        descriptor.value = new RegExp(value.source, value.flags);
        break;
      case value instanceof Object:
        descriptor.value = clone(value);
        break;
    }
    defineProperty(out, key, descriptor);
  });
  return out;
};
```
