### ISSUE TITLE
deepMerge overwriting not merging when more than 1 source is passed in.

### ISSUE THREAD

**Issue by nickyblissAviva** [WebReflection/cloner#7]
When using deepMerge it works as expected when simply passing in a target and one source but if you pass in further sources it merges the first then it seems to copy the subsequent ones meaning you loose data.

For example:

Source 1 contains:
```javascript
source1 = {
	oWallet : {
		nextButton : 'Next',
		previousButton : 'Previous',
	},
}
```

Source 2 contains:
```javascript
source2 = {
	oWallet : {
		nextButton : 'Avancer',
	},
}
```

Calling:
```javascript
cloner.deep.merge({}, source1, source2)
```

Results in:
```javascript
{
	oWallet : {
		nextButton : 'Avancer',
	},
}
```

Expected:
```javascript
{
	oWallet : {
		nextButton : 'Avancer',
		previousButton : 'Previous',
	},
}
```

Calling the following gives the expected result but is messy
```javascript
result = cloner.deep.merge({}, source1);
result = cloner.deep.merge(result, source2);
```

**Comment by WebReflection** [comment]
https://github.com/WebReflection/cloner/issues/6#issuecomment-613992543

**Comment by WebReflection** [comment]
https://github.com/WebReflection/cloner/issues/6#issuecomment-614510695
